### ISSUE TITLE
FHEM update not working - unexpecte size

### ISSUE THREAD

**Issue by verybadsoldier** [patrickjahns/esp_rgbww_fhemmodule#14]
I tried to enter this repo as update repo in FHEM.

`update add https://raw.githubusercontent.com/patrickjahns/esp_rgbww_fhemmodule/master/controls_ledcontroller.txt `

But then when issuing the update this error appears:
```
2016.12.31 00:03:39 1 : ledcontroller
2016.12.31 00:03:39 1 : UPD FHEM/32_LedController.pm
2016.12.31 00:03:40 1 : Got 43533 bytes for FHEM/32_LedController.pm, expected 15330
2016.12.31 00:03:40 1 : aborting.
```

Probably the file sizes in the control.txt does not match the actual size?

**Comment by pljakobs** [comment]
ich hab die Dateigröße angepasst und gleichzeitig den letzten devel change gemerged. Bei mir hat das Update jetzt funktioniert.
